"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
const address_1 = require("./address");
const article_1 = require("./article");
const blog_1 = require("./blog");
const cart_1 = require("./cart");
const collection_1 = require("./collection");
const customer_1 = require("./customer");
const discount_1 = require("./discount");
const discountapplication_1 = require("./discountapplication");
const discountallocation_1 = require("./discountallocation");
const fullfillment_1 = require("./fullfillment");
const image_1 = require("./image");
const lineItem_1 = require("./lineItem");
const order_1 = require("./order");
const partner_1 = require("./partner");
const product_1 = require("./product");
const search_1 = require("./search");
const sellingplan_1 = require("./sellingplan");
const sellingplanallocation_1 = require("./sellingplanallocation");
const sellingplangroup_1 = require("./sellingplangroup");
const store_1 = require("./store");
const variant_1 = require("./variant");
const shop_1 = require("./shop");
const unitpricemeasurement_1 = require("./unitpricemeasurement");
const supplier_1 = require("./supplier");
const response_1 = require("./response");
var MyModel;
(function (MyModel) {
    address_1.default;
    article_1.default;
    blog_1.default;
    cart_1.default;
    collection_1.default;
    customer_1.default;
    order_1.default;
    discountapplication_1.default;
    discount_1.default;
    fullfillment_1.default;
    image_1.default;
    lineItem_1.default;
    discountallocation_1.default;
    partner_1.default;
    product_1.default;
    sellingplan_1.default;
    sellingplanallocation_1.default;
    sellingplangroup_1.default;
    store_1.default;
    variant_1.default;
    shop_1.default;
    unitpricemeasurement_1.default;
    supplier_1.default;
    search_1.default;
    response_1.default;
})(MyModel || (MyModel = {}));
exports.default = MyModel;
