import DiscountAllocation from "./discountallocation";
import Fullfillment from "./fullfillment";
import Product from "./product";
import SellingPlanAllocation from "./sellingplanallocation";
import UnitPriceMeasurement from "./unitpricemeasurement";
import Variant from "./variant";
export default class LineItem {
    constructor(init?: Partial<LineItem>);
    price: number;
    discount_allocations: DiscountAllocation;
    final_line_price: number;
    final_price: number;
    fulfillment: Fullfillment;
    fulfillment_service: any;
    gift_card: boolean;
    grams: number;
    id: string;
    image: string;
    key: string;
    line_level_discount_allocations: DiscountAllocation;
    line_level_total_discount: number;
    message: string;
    options_with_values: Product[];
    original_price: number;
    product: Product;
    product_id: string;
    properties: [];
    quantity: number;
    requires_shipping: boolean;
    selling_plan_allocation: SellingPlanAllocation;
    sku: number;
    successfully_fulfilled_quantity: number;
    taxable: boolean;
    title: string;
    unit_price: number;
    unit_price_measurement: UnitPriceMeasurement;
    url: string;
    url_to_remove: string;
    variant: Variant;
    variant_id: string;
    vendor: any;
}
